from typing import Protocol, List, Dict, Any, Optional, Union

class IUserRepository(Protocol):
    async def get_user(self, user_id: int) -> Optional[Dict]: ...
    async def create_user(self, user_id: int, username: Optional[str] = None) -> None: ...
    async def is_admin(self, user_id: int) -> bool: ...

class IAttachmentRepository(Protocol):
    async def get_all_attachments(self, category: str, weapon: str, mode: str = 'br') -> List[Dict]: ...
    async def get_top_attachments(self, category: str, weapon: str, mode: str = 'br') -> List[Dict]: ...
    async def search(self, query: str) -> List[Dict]: ...
    async def track_attachment_view(self, user_id: int, attachment_id: int) -> None: ...

class IAnalyticsRepository(Protocol):
    async def track_search(self, user_id: int, query: str, results_count: int, duration_ms: float) -> None: ...
    async def get_search_stats(self, days: int = 7) -> List[Dict]: ...
    async def get_daily_usage_stats(self, days: int = 7) -> List[Dict]: ...
    async def get_user_leaderboard(self, days: int = 7, limit: int = 10) -> List[Dict]: ...

class ITicketRepository(Protocol):
    async def create_ticket(self, user_id: int, subject: str, message: str) -> int: ...
    async def get_attachment_stats(self, attachment_id: int, period: str = 'all') -> Dict: ...
